title: Servicio

fields:
  photo:
    label: Imagen de servicio
    type: files
    max: 1
    width: 1/2
    layout: cards
    size: huge
  text:
    label: Descripción de servicio
    type: textarea
    width: 1/2
    