title: Site

columns:
  left:
    width: 1/2
    sections:
      pages:
        headline: Páginas
        templates:
          - home
          - services
          - catalog
          - about
          - contact
          - support
          - ayuda
          - blog

  right: 
    width: 1/2
    sections:
    fields:
      nombre:
        type: text
        label: Nombre de la empresa
      telefono:
        type: tel
        label: Teléfono
        icon: phone
        width: 1/2
      whatsapp:
        type: tel
        label: Teléfono 2
        icon: phone
        width: 1/2
      mail:
        type: email
        label: Correo electrónico
        width: 1/2
      calle:
        type: text
        label: Calle
        width: 1/2
      numero:
        type: text
        label: Número
        width: 1/2
      colonia:
        type: text
        label: Colonia
        width: 1/2
      ciudad:
        type: text
        label: Ciudad
        width: 1/2
      estado:
        type: text
        label: Estado
        width: 1/2
      codigo:
        type: text
        label: Código Postal
        width: 1/2
      facebook:
        type: url
        label: Facebook
        icon: Facebook
        width: 1/2
      whatsapp:
        type: url
        label: Whatsapp
        icon: Whatsapp
      youtube:
        type: url
        label: youtube
        icon: youtube


